# (OpenAI) 대화 모델 설정
CHAT_MODEL_NAME = "gpt-4.1-mini"
CHAT_TEMPERATURE = 0.7
CHAT_MAX_TOKENS = 800
CHAT_TIMEOUT = 30.0

# (OpenAI) 요약 모델 설정
SUMMARY_MODEL_NAME = "gpt-4o-mini"
SUMMARY_TEMPERATURE = 0.3
SUMMARY_TIMEOUT = 30.0
