# (OpenAI) 대화 모델 설정
CHAT_MODEL_NAME = "gpt-4.1-mini"
CHAT_TEMPERATURE = 0.0
CHAT_MAX_TOKENS = 500
CHAT_TIMEOUT = 10.0

# (OpenAI) 온보딩 모델 설정
ONBOARDING_MODEL_NAME = "gpt-4.1-mini"
ONBOARDING_TEMPERATURE = 0.0
ONBOARDING_MAX_TOKENS = 500
ONBOARDING_TIMEOUT = 10.0

# (OpenAI) 요약 모델 설정
SUMMARY_MODEL_NAME = "gpt-4.1-mini"
SUMMARY_TEMPERATURE = 0.0
SUMMARY_MAX_TOKENS = 500
SUMMARY_TIMEOUT = 10.0
